### PR TITLE
apinatomy.py first pass at adding support for neru-7

### PR DESCRIPTION
**Pull request by tgbugs**
https://scicrunch.org/api/1/sparc-scigraph/dynamic/demos/apinat/neru-7/ilxtr:neuron-type-keast-6.json

### CODE REVIEW

**Comment by dbrnz** [comment]
What does `neru-7` provide, compared to `neru-6`? Will merging this PR break processing of `neru-6` queries??

**Comment by tgbugs** [comment]
`neru-7` is required to get the expected results out of staging due to a change from `inheritedExternal` to `inheritedOntologyTerms`, the PR should have no impact on `neru-6` processing so it should be possible to run the code against sckan-scigraph and sparc-scigraph and get the same results despite the changes in the ApiNATOMY schema between the endpoints.

**Comment by tgbugs** [comment]
I have one more commit to add to dispatch on staging vs prod.

**Comment by tgbugs** [comment]
When I run `examples/keast.py` I now get the same results from staging and production.

**Comment by dbrnz** [comment]
Thanks Tom!

**Pull request merged**
